# Generated by Django 5.1.3 on 2024-11-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_participant_password_participant_signup_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='gift_preference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='assigned_name',
            field=models.CharField(default='Unassigned - Waiting for everyone to join', max_length=100),
        ),
    ]
